---
abstract: 'Rule based Hash converter.'
author:
  - 'Hiroyoshi Houchi <hixi@cpan.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.6.2, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hash-Convert
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Hash::Convert:
    file: lib/Hash/Convert.pm
    version: 0.01
requires:
  B::Deparse: 0
  Carp: 0
  Data::Dumper: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/hixi-hyi/p5-Hash-Convert/issues
  homepage: https://github.com/hixi-hyi/p5-Hash-Convert
  repository: git://github.com/hixi-hyi/p5-Hash-Convert.git
version: 0.01
x_contributors:
  - 'Hiroyoshi Houchi <git@hixi-hyi.com>'
